### ISSUE TITLE
运行脚本出错 munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by 895515845** [lengjibo/FourEye#12]
![image](https://user-images.githubusercontent.com/43722004/105814392-50f3af00-5fec-11eb-9584-2306654b7356.png)
运行就这样，不管输入什么都会这样，重新git clone 也是一样，好奇怪。。。

**Comment by 895515845** [comment]
![image](https://user-images.githubusercontent.com/43722004/105814555-8bf5e280-5fec-11eb-8480-5dae8af659da.png)

**Comment by lengjibo** [comment]
我无法复现该错误...
