### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by wakaka123wakaka** [lengjibo/FourEye#6]
麻烦表哥看看
![image](https://user-images.githubusercontent.com/34087959/104419609-a921be80-55b3-11eb-8879-a5648d685558.png)

**Comment by zhzyker** [comment]
@wakaka123wakaka  参考 https://github.com/lengjibo/FourEye/issues/2

**Comment by wakaka123wakaka** [comment]
@zhzyker 谢谢表哥，问题解决了 就是生成的木马，无法上线

**Comment by wakaka123wakaka** [comment]
已经解决了 ，每次生成新的免杀马必须删除之前的否则无效
